from cryptography.fernet import Fernet
import time
import turtle
print("ByData Starting.....")
time.sleep(2)
print("..........ByData..........")
time.sleep(2)
turtle.speed(1)
turtle.penup()
turtle.goto(-250,150)
turtle.right(90)
turtle.pendown()
turtle.forward(150)
turtle.penup()
turtle.goto(-250,75)
turtle.pendown()
turtle.left(90)
turtle.forward(65)
turtle.penup()
turtle.goto(-185,150)
turtle.right(90)
turtle.pendown()
turtle.forward(150)
turtle.penup()
turtle.goto(-155,150)
turtle.pendown()
turtle.forward(150)
turtle.goto(-155,150)
turtle.left(90)
turtle.forward(65)
turtle.penup()
turtle.goto(-155,75)
turtle.pendown()
turtle.forward(65)
turtle.penup()
turtle.goto(-155,0)
turtle.pendown()
turtle.forward(65)
turtle.penup()
turtle.goto(-60,150)
turtle.pendown()
turtle.right(90)
turtle.forward(150)
turtle.penup()
turtle.goto(-60,0)
turtle.pendown()
turtle.left(90)
turtle.forward(75)
turtle.penup()
turtle.goto(35,150)
turtle.pendown()
turtle.right(90)
turtle.forward(150)
turtle.penup()
turtle.goto(35,0)
turtle.pendown()
turtle.left(90)
turtle.forward(75)
turtle.penup()
turtle.goto(180,0)
turtle.pendown()
turtle.circle(75)
turtle.bye()
print("ByData initialized successfully...")
time.sleep(2)
giris=input("ByData Veri Tabanina Girmek İçin Adinizi Giriniz...:")
time.sleep(2)
print("....................")
time.sleep(2)
print("Hoşgeldiniz Sayin",giris)
def dataİslemi():
    print("Bir txt oluşturmak için txt yi açmak istediğin yolu ve ardindan ismini yaz.")
    yeniDataOlustur=input("Data olusturmak istediğin dosyanin yolunu ve ismini yaz...:")
    dataVeriYazdirma= open(yeniDataOlustur,"w")
    time.sleep(2)
    yazdirma=input("Verini düzenlemek istiyorsan bu kutucuğa yazarak düzenleyebilirsiniz...:")
    dataVeriYazdirma.write(yazdirma)
    time.sleep(2)
    print("Dataniniz başarili bir şekilde oluşruldu.")
    print("ByData'da yeni veri oluşturmak istemiyorsan sağ üst köşede bulunan 'x' tuşuna basarak çikabilirsin")
    sifre= Fernet.generate_key()
    with open("sifredosyasi.key", "wb") as sifredosyasi:
        sifredosyasi.write(sifre)
        f= Fernet(sifre)
    with open( yeniDataOlustur, "rb") as originalFile:
        original= originalFile.read()
        encrypted = f.encrypt(original)
    with open ("şifreli_"+yeniDataOlustur, "wb") as sifrelenmisDosya:
        sifrelenmisDosya.write(sifre)
while True:
    dataİslemi()
    time.sleep(2)